name: Deploy or Push Changes

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # This line gives the bot permission to push commits or tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Your other steps here...

      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin main
